FROM docker.io/arm64v8/opensuse:leap
RUN zypper install -y wget xorriso mkisofs tar
RUN zypper install -y inst-source-utils mksusecd
RUN zypper install -y git osc build hostname sudo perl-DateTime-Format-DateParse make gcc
RUN zypper update -y

